### ISSUE TITLE
Difference from react-joi-forms?

### ISSUE THREAD

**Issue by rclai** [kjanoudi/joiful-react-forms#2]
How is this different from [this](https://github.com/appersonlabs/react-joi-forms).

**Comment by kjanoudi** [comment]
@rclai hey there. I started to use react-joi-forms and found a number of issues that made it less than useful for my purposes. I tried to fork off the project, but found that I would not be able to merge in any updates, so I chose to rewrite the majority of the codebase with the inspiration from @appersonlabs's version.

A number of improvements have been made:
- Updated to ES2015/6
- Add more customizing to the input types passed through to the builder by allowing you to pass in any input props to the components as well. 
- Support populating a form from something like Redux where it's populated from state/a database on mount/willreceiveprops.
- Add form re-rendering when parent props change
- Remove requirements for labels on the fields
- Change the way we pass in information to the input elements. No more metadata wrangling, just pass it in as a prop like normal components
- Moved validations to within each input element to improve error handling
- Added ability to show a single field and pass it properties rather than having it as a FormSection
- Using lodash where possible rather than rewriting the methods from lodash on our own.

I believe react-joi-forms is more suitable when trying to render a simple form straight from schema. This port is more viable for advanced forms, dealing with databases and using Redux, with advanced styling where customizability is more important than simplicity of generating the form.

It's not really ready for mass use right now, that's why there isn't a Readme yet :)

Hope that helps!

**Comment by kjanoudi** [comment]
@rclai the component is now ready for mass use, with a Readme including the instructions. Hope that answers your question!
